using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GAP.Base.Dto
{
    public class MadresBeneficiariosDto
    {
        #region Totales
        public Int64 IdSalaCuna { get; set; }
        public String NombreSalaCuna { get; set; }
        public Decimal Madres18OMenos { get; set; }
        public Decimal MadresDe19A24 { get; set; }
        public Decimal Madres25OMas { get; set; }
        public Decimal MadresSinEdad { get; set; }
        public Decimal TotalMadres { get; set; }
        #endregion

        #region Datos Madres 18 años
        public Decimal ECSinDescripcion18 { get; set; }
        public Decimal ECCelibe18 { get; set; }
        public Decimal ECSeparadoDeHecho18 { get; set; }
        public Decimal ECReligioso18 { get; set; }
        public Decimal ECOtros18 { get; set; }
        public Decimal ECUnionConAntecedentes18 { get; set; }
        public Decimal ECLaicoConsagrado18 { get; set; }
        public Decimal ECUnionDeHecho18 { get; set; }
        public Decimal ECSeparadoLegal18 { get; set; }
        public Decimal ECViudo18 { get; set; }
        public Decimal ECSoltero18 { get; set; }
        public Decimal ECCasado18 { get; set; }
        public Decimal ECDivorciado18 { get; set; }
        public Decimal ECSinEstadoCivil18 { get; set; }
        public Decimal ECTotal18 { get; set; }
        public Decimal NEJardin18 { get; set; }
        public Decimal NEPreescolar18 { get; set; }
        public Decimal NEPriPrimerGrado18 { get; set; }
        public Decimal NEPriSegundoGrado18 { get; set; }
        public Decimal NEPriTercerGrado18 { get; set; }
        public Decimal NEPriCuartoGrado18 { get; set; }
        public Decimal NEPriQuitoGrado18 { get; set; }
        public Decimal NEPriSextoGrado18 { get; set; }
        public Decimal NEPriSeptimoGrado18 { get; set; }
        public Decimal NEPriIncompleto18 { get; set; }
        public Decimal NEPriCompleto18 { get; set; }
        public Decimal NESecPrimerAnio18 { get; set; }
        public Decimal NESecSegundoAnio18 { get; set; }
        public Decimal NESecTercerAnio18 { get; set; }
        public Decimal NESecCuartoAnio18 { get; set; }
        public Decimal NESecQuintoAnio18 { get; set; }
        public Decimal NESecIncompleto18 { get; set; }
        public Decimal NESecCompleto18 { get; set; }
        public Decimal NETercPrimerAnio18 { get; set; }
        public Decimal NETercSegundoAnio18 { get; set; }
        public Decimal NETercTercerAnio18 { get; set; }
        public Decimal NETercIncompleto18 { get; set; }
        public Decimal NETercCompleto18 { get; set; }
        public Decimal NEUnivPrimerAnio18 { get; set; }
        public Decimal NEUnivSegundoAnio18 { get; set; }
        public Decimal NEUnivTercerAnio18 { get; set; }
        public Decimal NEUnivCuartoAnio18 { get; set; }
        public Decimal NEUnivQuintoAnio18 { get; set; }
        public Decimal NEUnivSextoAnio18 { get; set; }
        public Decimal NEUnivIncompleto18 { get; set; }
        public Decimal NEUnivCompleto18 { get; set; }
        public Decimal NEDesconocida18 { get; set; }
        public Decimal NESinInstruccion18 { get; set; }
        public Decimal NESinNivelEscolaridad18 { get; set; }
        public Decimal NETotal18 { get; set; }
        public Decimal OCPatronOEmpleador18 { get; set; }
        public Decimal OCCuentaPropista18 { get; set; }
        public Decimal OCObreroOEmpleadoPrivado18 { get; set; }
        public Decimal OCObreroOEmpleadoPublico18 { get; set; }
        public Decimal OCServicioDomestico18 { get; set; }
        public Decimal OCJubilado18 { get; set; }
        public Decimal OCPensionado18 { get; set; }
        public Decimal OCChangas18 { get; set; }
        public Decimal OCDesempleado18 { get; set; }
        public Decimal OCAmaDeCasa18 { get; set; }
        public Decimal OCEstudiante18 { get; set; }
        public Decimal OCInactivo18 { get; set; }
        public Decimal OCSinOcupacion18 { get; set; }
        public Decimal OCTotal18 { get; set; }
        #endregion

        #region Datos Madres 19 a 25 años
        public Decimal ECSinDescripcion19A24 { get; set; }
        public Decimal ECCelibe19A24 { get; set; }
        public Decimal ECSeparadoDeHecho19A24 { get; set; }
        public Decimal ECReligioso19A24 { get; set; }
        public Decimal ECOtros19A24 { get; set; }
        public Decimal ECUnionConAntecedentes19A24 { get; set; }
        public Decimal ECLaicoConsagrado19A24 { get; set; }
        public Decimal ECUnionDeHecho19A24 { get; set; }
        public Decimal ECSeparadoLegal19A24 { get; set; }
        public Decimal ECViudo19A24 { get; set; }
        public Decimal ECSoltero19A24 { get; set; }
        public Decimal ECCasado19A24 { get; set; }
        public Decimal ECDivorciado19A24 { get; set; }
        public Decimal ECSinEstadoCivil19A24 { get; set; }
        public Decimal ECTotal19A24 { get; set; }
        public Decimal NEJardin19A24 { get; set; }
        public Decimal NEPreescolar19A24 { get; set; }
        public Decimal NEPriPrimerGrado19A24 { get; set; }
        public Decimal NEPriSegundoGrado19A24 { get; set; }
        public Decimal NEPriTercerGrado19A24 { get; set; }
        public Decimal NEPriCuartoGrado19A24 { get; set; }
        public Decimal NEPriQuitoGrado19A24 { get; set; }
        public Decimal NEPriSextoGrado19A24 { get; set; }
        public Decimal NEPriSeptimoGrado19A24 { get; set; }
        public Decimal NEPriIncompleto19A24 { get; set; }
        public Decimal NEPriCompleto19A24 { get; set; }
        public Decimal NESecPrimerAnio19A24 { get; set; }
        public Decimal NESecSegundoAnio19A24 { get; set; }
        public Decimal NESecTercerAnio19A24 { get; set; }
        public Decimal NESecCuartoAnio19A24 { get; set; }
        public Decimal NESecQuintoAnio19A24 { get; set; }
        public Decimal NESecIncompleto19A24 { get; set; }
        public Decimal NESecCompleto19A24 { get; set; }
        public Decimal NETercPrimerAnio19A24 { get; set; }
        public Decimal NETercSegundoAnio19A24 { get; set; }
        public Decimal NETercTercerAnio19A24 { get; set; }
        public Decimal NETercIncompleto19A24 { get; set; }
        public Decimal NETercCompleto19A24 { get; set; }
        public Decimal NEUnivPrimerAnio19A24 { get; set; }
        public Decimal NEUnivSegundoAnio19A24 { get; set; }
        public Decimal NEUnivTercerAnio19A24 { get; set; }
        public Decimal NEUnivCuartoAnio19A24 { get; set; }
        public Decimal NEUnivQuintoAnio19A24 { get; set; }
        public Decimal NEUnivSextoAnio19A24 { get; set; }
        public Decimal NEUnivIncompleto19A24 { get; set; }
        public Decimal NEUnivCompleto19A24 { get; set; }
        public Decimal NEDesconocida19A24 { get; set; }
        public Decimal NESinInstruccion19A24 { get; set; }
        public Decimal NESinNivelEscolaridad19A24 { get; set; }
        public Decimal NETotal19A24 { get; set; }
        public Decimal OCPatronOEmpleador19A24 { get; set; }
        public Decimal OCCuentaPropista19A24 { get; set; }
        public Decimal OCObreroOEmpleadoPrivado19A24 { get; set; }
        public Decimal OCObreroOEmpleadoPublico19A24 { get; set; }
        public Decimal OCServicioDomestico19A24 { get; set; }
        public Decimal OCJubilado19A24 { get; set; }
        public Decimal OCPensionado19A24 { get; set; }
        public Decimal OCChangas19A24 { get; set; }
        public Decimal OCDesempleado19A24 { get; set; }
        public Decimal OCAmaDeCasa19A24 { get; set; }
        public Decimal OCEstudiante19A24 { get; set; }
        public Decimal OCInactivo19A24 { get; set; }
        public Decimal OCSinOcupacion19A24 { get; set; }
        public Decimal OCTotal19A24 { get; set; }
        #endregion

        #region Datos Madres Mayor 25 años
        public Decimal ECSinDescripcion25 { get; set; }
        public Decimal ECCelibe25 { get; set; }
        public Decimal ECSeparadoDeHecho25 { get; set; }
        public Decimal ECReligioso25 { get; set; }
        public Decimal ECOtros25 { get; set; }
        public Decimal ECUnionConAntecedentes25 { get; set; }
        public Decimal ECLaicoConsagrado25 { get; set; }
        public Decimal ECUnionDeHecho25 { get; set; }
        public Decimal ECSeparadoLegal25 { get; set; }
        public Decimal ECViudo25 { get; set; }
        public Decimal ECSoltero25 { get; set; }
        public Decimal ECCasado25 { get; set; }
        public Decimal ECDivorciado25 { get; set; }
        public Decimal ECSinEstadoCivil25 { get; set; }
        public Decimal ECTotal25 { get; set; }
        public Decimal NEJardin25 { get; set; }
        public Decimal NEPreescolar25 { get; set; }
        public Decimal NEPriPrimerGrado25 { get; set; }
        public Decimal NEPriSegundoGrado25 { get; set; }
        public Decimal NEPriTercerGrado25 { get; set; }
        public Decimal NEPriCuartoGrado25 { get; set; }
        public Decimal NEPriQuitoGrado25 { get; set; }
        public Decimal NEPriSextoGrado25 { get; set; }
        public Decimal NEPriSeptimoGrado25 { get; set; }
        public Decimal NEPriIncompleto25 { get; set; }
        public Decimal NEPriCompleto25 { get; set; }
        public Decimal NESecPrimerAnio25 { get; set; }
        public Decimal NESecSegundoAnio25 { get; set; }
        public Decimal NESecTercerAnio25 { get; set; }
        public Decimal NESecCuartoAnio25 { get; set; }
        public Decimal NESecQuintoAnio25 { get; set; }
        public Decimal NESecIncompleto25 { get; set; }
        public Decimal NESecCompleto25 { get; set; }
        public Decimal NETercPrimerAnio25 { get; set; }
        public Decimal NETercSegundoAnio25 { get; set; }
        public Decimal NETercTercerAnio25 { get; set; }
        public Decimal NETercIncompleto25 { get; set; }
        public Decimal NETercCompleto25 { get; set; }
        public Decimal NEUnivPrimerAnio25 { get; set; }
        public Decimal NEUnivSegundoAnio25 { get; set; }
        public Decimal NEUnivTercerAnio25 { get; set; }
        public Decimal NEUnivCuartoAnio25 { get; set; }
        public Decimal NEUnivQuintoAnio25 { get; set; }
        public Decimal NEUnivSextoAnio25 { get; set; }
        public Decimal NEUnivIncompleto25 { get; set; }
        public Decimal NEUnivCompleto25 { get; set; }
        public Decimal NEDesconocida25 { get; set; }
        public Decimal NESinInstruccion25 { get; set; }
        public Decimal NESinNivelEscolaridad25 { get; set; }
        public Decimal NETotal25 { get; set; }
        public Decimal OCPatronOEmpleador25 { get; set; }
        public Decimal OCCuentaPropista25 { get; set; }
        public Decimal OCObreroOEmpleadoPrivado25 { get; set; }
        public Decimal OCObreroOEmpleadoPublico25 { get; set; }
        public Decimal OCServicioDomestico25 { get; set; }
        public Decimal OCJubilado25 { get; set; }
        public Decimal OCPensionado25 { get; set; }
        public Decimal OCChangas25 { get; set; }
        public Decimal OCDesempleado25 { get; set; }
        public Decimal OCAmaDeCasa25 { get; set; }
        public Decimal OCEstudiante25 { get; set; }
        public Decimal OCInactivo25 { get; set; }
        public Decimal OCSinOcupacion25 { get; set; }
        public Decimal OCTotal25 { get; set; }
        #endregion

        #region Datos Madres SD
        public Decimal ECSinDescripcionSD { get; set; }
        public Decimal ECCelibeSD { get; set; }
        public Decimal ECSeparadoDeHechoSD { get; set; }
        public Decimal ECReligiosoSD { get; set; }
        public Decimal ECOtrosSD { get; set; }
        public Decimal ECUnionConAntecedentesSD { get; set; }
        public Decimal ECLaicoConsagradoSD { get; set; }
        public Decimal ECUnionDeHechoSD { get; set; }
        public Decimal ECSeparadoLegalSD { get; set; }
        public Decimal ECViudoSD { get; set; }
        public Decimal ECSolteroSD { get; set; }
        public Decimal ECCasadoSD { get; set; }
        public Decimal ECDivorciadoSD { get; set; }
        public Decimal ECSinEstadoCivilSD { get; set; }
        public Decimal ECTotalSD { get; set; }
        public Decimal NEJardinSD { get; set; }
        public Decimal NEPreescolarSD { get; set; }
        public Decimal NEPriPrimerGradoSD { get; set; }
        public Decimal NEPriSegundoGradoSD { get; set; }
        public Decimal NEPriTercerGradoSD { get; set; }
        public Decimal NEPriCuartoGradoSD { get; set; }
        public Decimal NEPriQuitoGradoSD { get; set; }
        public Decimal NEPriSextoGradoSD { get; set; }
        public Decimal NEPriSeptimoGradoSD { get; set; }
        public Decimal NEPriIncompletoSD { get; set; }
        public Decimal NEPriCompletoSD { get; set; }
        public Decimal NESecPrimerAnioSD { get; set; }
        public Decimal NESecSegundoAnioSD { get; set; }
        public Decimal NESecTercerAnioSD { get; set; }
        public Decimal NESecCuartoAnioSD { get; set; }
        public Decimal NESecQuintoAnioSD { get; set; }
        public Decimal NESecIncompletoSD { get; set; }
        public Decimal NESecCompletoSD { get; set; }
        public Decimal NETercPrimerAnioSD { get; set; }
        public Decimal NETercSegundoAnioSD { get; set; }
        public Decimal NETercTercerAnioSD { get; set; }
        public Decimal NETercIncompletoSD { get; set; }
        public Decimal NETercCompletoSD { get; set; }
        public Decimal NEUnivPrimerAnioSD { get; set; }
        public Decimal NEUnivSegundoAnioSD { get; set; }
        public Decimal NEUnivTercerAnioSD { get; set; }
        public Decimal NEUnivCuartoAnioSD { get; set; }
        public Decimal NEUnivQuintoAnioSD { get; set; }
        public Decimal NEUnivSextoAnioSD { get; set; }
        public Decimal NEUnivIncompletoSD { get; set; }
        public Decimal NEUnivCompletoSD { get; set; }
        public Decimal NEDesconocidaSD { get; set; }
        public Decimal NESinInstruccionSD { get; set; }
        public Decimal NESinNivelEscolaridadSD { get; set; }
        public Decimal NETotalSD { get; set; }
        public Decimal OCPatronOEmpleadorSD { get; set; }
        public Decimal OCCuentaPropistaSD { get; set; }
        public Decimal OCObreroOEmpleadoPrivadoSD { get; set; }
        public Decimal OCObreroOEmpleadoPublicoSD { get; set; }
        public Decimal OCServicioDomesticoSD { get; set; }
        public Decimal OCJubiladoSD { get; set; }
        public Decimal OCPensionadoSD { get; set; }
        public Decimal OCChangasSD { get; set; }
        public Decimal OCDesempleadoSD { get; set; }
        public Decimal OCAmaDeCasaSD { get; set; }
        public Decimal OCEstudianteSD { get; set; }
        public Decimal OCInactivoSD { get; set; }
        public Decimal OCSinOcupacionSD { get; set; }
        public Decimal OCTotalSD { get; set; }
        #endregion
    }
}